const Images ={
    angel: require('../images/ANGEL.jpg'),
    chooseImage: require('../images/addPhoto.png'),
    chatBg: require('../images/lamb.jpg'),
    photo: require('../images/photo.png'),
    sticker: require('../images/sticker.png'),
    send: require('../images/send.png'),
    hello: require('../images/hello.png'),
    rndm: require('../images/account.png'),
    stkr1 : require('../images/stkr 1.gif'),
    stkr2 : require('../images/stkr 2.gif'),
    stkr3 : require('../images/stkr 3.gif'),
    stkr4 : require('../images/stkr 4.gif'),
    stkr5 : require('../images/stkr 5.gif'),
    stkr6 : require('../images/stkr 6.gif'),
    stkr7 : require('../images/stkr 7.gif'),
    stkr8 : require('../images/stkr 8.gif'),
    stkr9 : require('../images/stkr 9.gif'),
    stkr10 : require('../images/stkr 10.gif'),
    stkr11 : require('../images/stkr 11.gif'),
    stkr12 : require('../images/stkr 12.gif'),
    stkr13 : require('../images/stkr 13.gif'),
    stkr14 : require('../images/stkr 14.gif'),
    stkr15 : require('../images/stkr 15.gif'),
    stkr16 : require('../images/stkr 16.gif'),
    stkr17 : require('../images/stkr 17.gif'),
    stkr18 : require('../images/stkr 18.gif'),
    stkr19 : require('../images/stkr 19.gif'),
    stkr20 : require('../images/stkr 20.gif'),
    stkr21 : require('../images/stkr 21.gif'),
    stkr22 : require('../images/stkr 22.gif'),
    stkr23 : require('../images/stkr 23.gif'),
    stkr24 : require('../images/stkr 24.gif'),
    stkr25 : require('../images/stkr 25.gif'),
    stkr26 : require('../images/stkr 26.gif'),
    stkr27 : require('../images/stkr 27.gif'),
    stkr28 : require('../images/stkr 28.gif'),
    stkr29 : require('../images/stkr 29.gif'),
    stkr30 : require('../images/stkr 30.gif'),
}


export default Images